import "./executes/_scrollMagic";
import "./executes/_openNav";
import "./executes/_movie";
import "./executes/_animation";
import "./executes/_swiper";
import "./executes/_fixed";
import "./executes/_tab";
import "./executes/_smoothScroll";
import "picturefill";
